yatube/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (CommentViewSet,
                    FollowViewSet,
                    GroupViewSet,
                    PostViewSet)

app_name = 'api'

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'posts/(?P<post_id>[0-9]+)/comments',
                CommentViewSet,
                basename='comments')
router.register(r'follow', FollowViewSet, basename='follow')

urlpatterns = [
    path('v1/', include('djoser.urls')),
    path('v1/', include('djoser.urls.jwt')),
    path('v1/', include(router.urls))
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('', views.index, name='index')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('redoc/', TemplateView.as_view(template_name='api/redoc.html'),
         name='redoc'),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название группы',
        max_length=200)
    slug = models.SlugField(
        verbose_name='Ссылка на группу',
        max_length=200,
        unique=True)
    description = models.TextField(
        verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Здесь будет текст вашего поста')
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text=('Можно выбрать группу,'
                   ' которой будет принадлежать пост'),
        related_name='posts'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Группа не выбрана'

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, Comment, Follow
from .utils import paginator

User = get_user_model()


def index(request):
    post_list = Post.objects.select_related('group').all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.all()
    page_obj = paginator(request, posts_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_list = Post.objects.filter(
        author=author).select_related('group')
    posts_count = posts_list.count()
    page_obj = paginator(request, posts_list)
    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_count': posts_count,
    }
    if not request.user.is_authenticated:
        return render(request, 'posts/profile.html', context)
    following = Follow.objects.filter(
        user=request.user,
        author=author
    )
    context['following'] = following
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    user = request.user
    post = get_object_or_404(Post, pk=post_id)
    posts_count = Post.objects.filter(author=post.author).count()
    comments = Comment.objects.filter(post_id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'posts_count': posts_count,
        'post': post,
        'user': user,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author_id = request.user.id
        post.save()
        return redirect('posts:profile', username=request.user)
    return render(request, 'posts/create_post.html',
                  {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author_id != request.user.id:
        return redirect('posts:post_detail', post_id=post_id)
    is_edit = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form,
                   'post': post,
                   'is_edit': is_edit})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follower_user = request.user
    user_following_authors = Follow.objects.filter(
        user=follower_user).values('author')
    posts = Post.objects.filter(author__in=user_following_authors)
    page_obj = paginator(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(
        user=request.user,
        author=author
    )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=author
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
    {% if is_edit %}
        Редактировать пост
    {% else %}
        Новый пост
    {% endif %}
{% endblock title %}
{% block content %}
    {% load user_filters %}
    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            {% if is_edit %}
                                Редактировать пост
                            {% else %}
                                Новый пост
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form method="POST"
                                    {% if action_url %}
                                  action="{% url action_url %}"
                                    {% endif %}
                            enctype="multipart/form-data"
                            >
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group row my-3 p-3"
                                            {% if field.field.required %}
                                         aria-required="true"
                                            {% else %}
                                         aria-required="false"
                                            {% endif %}
                                    >
                                        <label for="{{ field.id_for_label }}">
                                            {{ field.label }}
                                            {% if field.field.required %}
                                                <span class="required text-danger">*</span>
                                            {% endif %}
                                        </label>
                                        <div>
                                            {{ field|addclass:'form-control' }}
                                            {% if field.help_text %}
                                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                                    {{ field.help_text|safe }}
                                                </small>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endfor %}
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary">
                                        {% if is_edit %}
                                            Добавить
                                        {% else %}
                                            Сохранить
                                        {% endif %}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
    Подписки
{% endblock title %}
{% block content %}
    {% load thumbnail %}
    {% include 'posts/includes/switcher.html' %}
    <main>
        <div class="container py-5">
            <h1>
                Ваши подписки
            </h1>
            {% for post in page_obj %}
                <article>
                    <ul>
                        <li>
                            Автор: {{ post.author.get_full_name }}
                            <a href="{% url 'posts:profile' post.author %}">
                                все посты пользователя
                            </a>
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                        </li>
                    </ul>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                    <p>
                        {{ post.text }}
                    </p>
                    <a href="{% url 'posts:post_detail' post.pk %}">
                        подробная информация
                    </a>
                </article>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                        все записи группы
                    </a>
                {% endif %}
                {% if not forloop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
            {% include 'posts/includes/paginator.html' %}
        </div>
    </main>
{% endblock content %}

yatube/templates/posts/group_list.html
  {% extends 'base.html' %}
  {% block title %}
      {{ group.title }}
  {% endblock title %}
  {% block content %}
      {% load thumbnail %}
      <main>
          <div class="container py-5">
              <h1>
                  {{ group.title }}
              </h1>
              <p>
                  {{ group.description }}
              </p>
              {% for post in page_obj %}
                  <article>
                      <ul>
                          <li>
                              Автор: {{ post.author.get_full_name }}
                              <a href="{% url 'posts:profile' post.author %}">
                                  все посты пользователя
                              </a>
                          </li>
                          <li>
                              Дата публикации: {{ post.pub_date|date:"d E Y" }}
                          </li>
                      </ul>
                      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                          <img class="card-img my-2" src="{{ im.url }}">
                      {% endthumbnail %}
                      <p>
                          {{ post.text }}
                      </p>
                      <a href="{% url 'posts:post_detail' post.pk %}">
                          подробная информация
                      </a>
                  </article>
                  {% if not forloop.last %}
                      <hr>
                  {% endif %}
              {% endfor %}
              {% include 'posts/includes/paginator.html' %}
          </div>
      </main>
  {% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    Последние обновления на сайте
{% endblock title %}
{% block content %}
    {% load cache %}
    {% load thumbnail %}
    {% include 'posts/includes/switcher.html' %}
    <main>
        <div class="container py-5">
            <h1>
                Последние обновления на сайте
            </h1>
        {% cache 20 index_page page_obj.number %}
            {% for post in page_obj %}
                <article>
                    <ul>
                        <li>
                            Автор: {{ post.author.get_full_name }}
                            <a href="{% url 'posts:profile' post.author %}">
                                все посты пользователя
                            </a>
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                        </li>
                    </ul>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                    <p>
                        {{ post.text }}
                    </p>
                    <a href="{% url 'posts:post_detail' post.pk %}">
                        подробная информация
                    </a>
                </article>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                        все записи группы
                    </a>
                {% endif %}
                {% if not forloop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
        {% endcache %}
            {% include 'posts/includes/paginator.html' %}
        </div>
    </main>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    Пост {{ post.text|slice:":30" }}
{% endblock title %}
{% block content %}
    {% load thumbnail %}
    {% load user_filters %}
    <main>
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date }}
                    </li>
                    {% if post.group %}
                        <li class="list-group-item">
                            Группа: {{ post.group }}
                            <a href="{% url 'posts:group_list' post.group.slug %}">
                                все записи группы
                            </a>
                        </li>
                    {% endif %}
                    <li class="list-group-item">
                        Автор: {{ post.author }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора:
                        <span>
                            {{ posts_count }}
                        </span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author %}">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                    {{ post.text }}
                </p>
                {% if post.author_id == user.id %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                    редактировать запись
                </a>
                {% endif %}
            {% if user.is_authenticated %}
                <div class="card my-4">
                    <h5 class="card-header">Добавить комментарий:</h5>
                    <div class="card-body">
                        <form method="post" action="{% url 'posts:add_comment' post.id %}">
                            {% csrf_token %}
                            <div class="form-group mb-2">
                                {{ form.text|addclass:"form-control" }}
                            </div>
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            {% endif %}
                {% for comment in comments %}
                    <div class="media mb-4">
                        <div class="media-body">
                            <h5 class="mt-0">
                                <a href="{% url 'posts:profile' comment.author.username %}">
                                    {{ comment.author.username }}
                                </a>
                            </h5>
                            <p>
                                {{ comment.text }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </article>
        </div>
    </main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    {{ author }} профайл пользователя
{% endblock title %}
{% block content %}
    {% load thumbnail %}
    <main>
        <div class="container py-5">
            <div class="mb-5">
            <h1>
                Все посты пользователя {{ author }}
            </h1>
            <h3>
                Всего постов: {{ posts_count }}
            </h3>
            {% if author.id != request.user.id %}
                {% if following %}
                    <a class="btn btn-lg btn-light"
                       href="{% url 'posts:profile_unfollow' author.username %}"
                       role="button"
                    >
                        Отписаться
                    </a>
                {% else %}
                    <a class="btn btn-lg btn-primary"
                       href="{% url 'posts:profile_follow' author.username %}"
                       role="button"
                    >
                        Подписаться
                    </a>
                {% endif %}
            {% endif %}
            </div>
            <article>
                {% for posts in page_obj %}
                    <ul>
                        <li>
                            Дата публикации: {{ posts.pub_date|date:"d E Y" }}
                        </li>
                    </ul>
                    {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                    <p>
                        {{ posts.text }}
                    </p>
                    <a href="{% url 'posts:post_detail' posts.pk %}">
                        подробная информация
                    </a>
                    </article>
                    {% if posts.group %}
                        <p>
                            <a href="{% url 'posts:group_list' posts.group.slug %}">
                                все записи группы
                            </a>
                        </p>
                    {% endif %}
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            {% include 'posts/includes/paginator.html' %}
        </div>
    </main>
{% endblock content %}